import MovieInfo from "@/components/MovieInfo";
import { type NextPage } from "next";
import Head from "next/head";


const Home: NextPage = () => {


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <MovieInfo />
    </>
  );
};

export default Home;
